# Generated by Django 5.2.1 on 2025-06-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("artist_name", models.CharField(max_length=200)),
                (
                    "spotify_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acousticness", models.FloatField()),
                ("danceability", models.FloatField()),
                ("energy", models.FloatField()),
                ("instrumentalness", models.FloatField()),
                ("liveness", models.FloatField()),
                ("loudness", models.FloatField()),
                ("spechiness", models.FloatField()),
                ("tempo", models.FloatField()),
                ("valence", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("song_title", models.CharField(max_length=200)),
                (
                    "isrc",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommender.artist",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommender.songanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.song",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserPlaylist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("playlist_name", models.CharField(max_length=200)),
                (
                    "songs",
                    models.ManyToManyField(
                        through="recommender.PlaylistSong", to="recommender.song"
                    ),
                ),
                (
                    "spotify_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userspotifyprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playlistsong",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recommender.userplaylist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playlistsong",
            unique_together={("playlist", "song")},
        ),
    ]
