# Generated by Django 5.2.1 on 2025-05-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("artist_name", models.CharField(max_length=200)),
                (
                    "spotify_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acousticness", models.FloatField()),
                ("danceability", models.FloatField()),
                ("energy", models.FloatField()),
                ("instrumentalness", models.FloatField()),
                ("liveness", models.FloatField()),
                ("loudness", models.FloatField()),
                ("spechiness", models.FloatField()),
                ("tempo", models.FloatField()),
                ("valence", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("song_title", models.CharField(max_length=200)),
                (
                    "isrc",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.artist",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.songanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("playlist_name", models.CharField(max_length=200)),
                ("songs", models.ManyToManyField(to="recommender.song")),
            ],
        ),
    ]
