# Generated by Django 5.2.1 on 2025-06-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplaylist",
            name="spotify_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_playlist",
                to="accounts.userspotifyprofile",
            ),
        ),
    ]
