# Generated by Django 5.2.1 on 2025-06-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userspotifyprofile_last_synced"),
        ("recommender", "0002_alter_userplaylist_spotify_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlistsong",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_songs",
                to="recommender.userplaylist",
            ),
        ),
        migrations.AlterField(
            model_name="userplaylist",
            name="spotify_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_playlists",
                to="accounts.userspotifyprofile",
            ),
        ),
    ]
