# Generated by Django 5.2.1 on 2025-06-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_alter_playlistsong_playlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplaylist",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
