# Generated by Django 5.2.1 on 2025-06-18 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0004_userplaylist_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="songanalysis",
            old_name="spechiness",
            new_name="speechiness",
        ),
        migrations.AlterField(
            model_name="playlistsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recommender.song"
            ),
        ),
    ]
