# Generated by Django 5.2.1 on 2025-06-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0005_rename_spechiness_songanalysis_speechiness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.CharField(default=""),
        ),
        migrations.AddField(
            model_name="song",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
