# Generated by Django 5.2.1 on 2025-06-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0006_song_album_song_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
