# Generated by Django 5.2.1 on 2025-06-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0007_song_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="image_url",
            field=models.URLField(default="/default-album-art.jpg"),
        ),
    ]
