# Generated by Django 5.2.1 on 2025-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0009_userplaylist_spotify_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="spotify_uri",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
