# Generated by Django 5.2.1 on 2025-07-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0010_song_spotify_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
