# Generated by Django 5.2.1 on 2025-06-13 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userspotifyprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userspotifyprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spotify_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
