# Generated by Django 5.2.1 on 2025-05-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="spotify_username",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
