# Generated by Django 5.2.1 on 2025-06-13 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userspotifyprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspotifyprofile",
            name="last_synced",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
