# Generated by Django 5.2.1 on 2025-06-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userspotifyprofile_last_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspotifyprofile",
            name="scopes_granted",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
