# Generated by Django 5.2.1 on 2025-06-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userspotifyprofile_scopes_granted"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspotifyprofile",
            name="artists_discovered",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userspotifyprofile",
            name="playlists_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userspotifyprofile",
            name="songs_recommended",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
