# Generated by Django 5.2.1 on 2025-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userspotifyprofile_artists_discovered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userspotifyprofile",
            name="spotify_profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
